### ISSUE TITLE
Image scan has detect several vulnerabilites

### ISSUE THREAD

**Issue by albertschwarzkopf** [bitnami/bitnami-docker-nginx-exporter#1]
### Name and Version

nginx-exporter:0.10.0

### What steps will reproduce the bug?

Trivy image scanner has detect several vulnerabilites:

`trivy image public.ecr.aws/bitnami/nginx-exporter:0.10.0`

public.ecr.aws/bitnami/nginx-exporter:0.8.0 (debian 10.8)
Total: 206 (UNKNOWN: 0, LOW: 117, MEDIUM: 28, HIGH: 48, CRITICAL: 13)

opt/bitnami/nginx-exporter/bin/nginx-prometheus-exporter (gobinary)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

Full report: 
[nginx-exporter.txt](https://github.com/bitnami/bitnami-docker-nginx-exporter/files/8110392/nginx-exporter.txt)

### What is the expected behavior?

An image without "CRITICAL" or "HIGH" vulnerabilites.

### What do you see instead?

48 High and 13 Critical vulnerabilities, based on NVD (avd.aquasec.com/nvd)

### Additional information

Could you please fix the "HIGH" and "CRITICAL" issues?

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Please note that the reported security issues are because of system packages. As soon as the upstream OS releases fixed versions of the packages, a new container will be released fixing the issue.
